-- Auto-generated palette from theme.yml
-- Theme: Unknown
-- Source: Unknown

local M = {}

M.palette = {
  -- Base16 palette
  base00 = "#192330",
  base01 = "#212e3f",
  base02 = "#29394f",
  base03 = "#738091",
  base04 = "#71839b",
  base05 = "#cdcecf",
  base06 = "#d6d6d7",
  base07 = "#aeafb0",
  base08 = "#c94f6d",
  base09 = "#f4a261",
  base0A = "#dbc074",
  base0B = "#81b29a",
  base0C = "#63cdcf",
  base0D = "#719cd6",
  base0E = "#9d79d6",
  base0F = "#d67ad2",

  -- Extended palette
  bg0 = "#131a24",
  bg1 = "#192330",
  bg2 = "#212e3f",
  bg3 = "#29394f",
  bg4 = "#39506d",
  fg0 = "#d6d6d7",
  fg1 = "#cdcecf",
  fg2 = "#aeafb0",
  fg3 = "#71839b",
  sel0 = "#2b3b51",
  sel1 = "#3c5372",
  comment = "#738091",
  orange = "#f4a261",
  pink = "#d67ad2",
  diagnostic_error = "#c94f6d",
  diagnostic_warning = "#dbc074",
  diagnostic_info = "#719cd6",
  diagnostic_hint = "#81b29a",
  diagnostic_ok = "#81b29a",
  syntax_comment = "#738091",
  syntax_string = "#81b29a",
  syntax_function = "#86abdc",
  syntax_keyword = "#9d79d6",
  syntax_type = "#dbc074",
  syntax_number = "#f4a261",
  syntax_constant = "#f6b079",
  syntax_operator = "#aeafb0",
  syntax_variable = "#dfdfe0",
  syntax_parameter = "#7ad5d6",
  syntax_field = "#719cd6",
  syntax_conditional = "#baa1e2",
  syntax_preproc = "#dc8ed9",
  syntax_regex = "#e0c988",
  syntax_punctuation = "#aeafb0",
  syntax_tag = "#9d79d6",
  syntax_attribute = "#86abdc",
  syntax_special = "#86abdc",
  ui_accent = "#719cd6",
  ui_border = "#39506d",
  ui_selection = "#2b3b51",
  ui_float_bg = "#131a24",
  ui_cursor_line = "#29394f",
  git_add = "#81b29a",
  git_change = "#dbc074",
  git_delete = "#c94f6d",
}

M.special = {
  background = "#192330",
  foreground = "#cdcecf",
  cursor = "#cdcecf",
  cursor_text = "#192330",
  selection_bg = "#2b3b51",
  selection_fg = "#cdcecf",
  border = "#39506d",
  panel = "#131a24",
}

-- Semantic theme colors derived from palette
M.theme = {
  ui = {
    bg = M.palette.base00,
    bg_dim = M.palette.bg_dim or M.palette.base00,
    bg_p1 = M.palette.base01,
    bg_p2 = M.palette.base02,
    bg_m1 = M.palette.base01,
    bg_m3 = M.palette.base01,
    bg_gutter = M.palette.base00,
    bg_visual = M.palette.base02,
    bg_search = M.palette.base0A,
    fg = M.palette.base05,
    fg_dim = M.palette.base04,
    fg_reverse = M.palette.base00,
    special = M.palette.base0C,
    nontext = M.palette.base03,
    whitespace = M.palette.base02,
    float = {
      fg = M.palette.base05,
      bg = M.palette.base01,
      fg_border = M.palette.base04,
      bg_border = M.palette.base01,
    },
    pmenu = {
      fg = M.palette.base05,
      fg_sel = M.palette.base05,
      bg = M.palette.base01,
      bg_sel = M.palette.base02,
      bg_sbar = M.palette.base02,
      bg_thumb = M.palette.base03,
    },
  },
  syn = {
    comment = M.palette.syntax_comment,
    string = M.palette.syntax_string,
    number = M.palette.syntax_number,
    constant = M.palette.syntax_constant,
    identifier = M.palette.base0D,
    parameter = M.palette.syntax_parameter,
    fun = M.palette.syntax_function,
    statement = M.palette.base08,
    keyword = M.palette.syntax_keyword,
    operator = M.palette.syntax_operator,
    preproc = M.palette.syntax_preproc,
    type = M.palette.syntax_type,
    special1 = M.palette.base09,
    special2 = M.palette.base08,
    special3 = M.palette.base0C,
    punct = M.palette.base09,
    regex = M.palette.syntax_regex,
    deprecated = M.palette.base03,
  },
  diag = {
    error = M.palette.diagnostic_error,
    warning = M.palette.diagnostic_warning,
    info = M.palette.diagnostic_info,
    hint = M.palette.diagnostic_hint,
    ok = M.palette.diagnostic_ok,
  },
  vcs = {
    added = M.palette.git_add,
    changed = M.palette.git_change,
    removed = M.palette.git_delete,
  },
  diff = {
    add = "#2e4045",
    change = "#3a3e3c",
    delete = "#553245",
    text = "#5b5847",
  },
}

return M
