-- Auto-generated palette from theme.yml
-- Theme: Unknown
-- Source: Unknown

local M = {}

M.palette = {
  -- Base16 palette
  base00 = "#152528",
  base01 = "#1d3337",
  base02 = "#254147",
  base03 = "#6d7f8b",
  base04 = "#587b7b",
  base05 = "#e6eaea",
  base06 = "#eaeeee",
  base07 = "#cbd9d8",
  base08 = "#e85c51",
  base09 = "#ff8349",
  base0A = "#fda47f",
  base0B = "#7aa4a1",
  base0C = "#a1cdd8",
  base0D = "#5a93aa",
  base0E = "#ad5c7c",
  base0F = "#cb7985",

  -- Extended palette
  bg0 = "#0f1c1e",
  bg1 = "#152528",
  bg2 = "#1d3337",
  bg3 = "#254147",
  bg4 = "#2d4f56",
  fg0 = "#eaeeee",
  fg1 = "#e6eaea",
  fg2 = "#cbd9d8",
  fg3 = "#587b7b",
  sel0 = "#293e40",
  sel1 = "#425e5e",
  comment = "#6d7f8b",
  orange = "#ff8349",
  pink = "#cb7985",
  diagnostic_error = "#e85c51",
  diagnostic_warning = "#fda47f",
  diagnostic_info = "#5a93aa",
  diagnostic_hint = "#7aa4a1",
  diagnostic_ok = "#7aa4a1",
  syntax_comment = "#6d7f8b",
  syntax_string = "#7aa4a1",
  syntax_function = "#73a3b7",
  syntax_keyword = "#ad5c7c",
  syntax_type = "#fda47f",
  syntax_number = "#ff8349",
  syntax_constant = "#ff9664",
  syntax_operator = "#cbd9d8",
  syntax_variable = "#ebebeb",
  syntax_parameter = "#afd4de",
  syntax_field = "#5a93aa",
  syntax_conditional = "#b97490",
  syntax_preproc = "#d38d97",
  syntax_regex = "#fdb292",
  syntax_punctuation = "#cbd9d8",
  syntax_tag = "#ad5c7c",
  syntax_attribute = "#73a3b7",
  syntax_special = "#73a3b7",
  ui_accent = "#5a93aa",
  ui_border = "#2d4f56",
  ui_selection = "#293e40",
  ui_float_bg = "#0f1c1e",
  ui_cursor_line = "#254147",
  git_add = "#7aa4a1",
  git_change = "#fda47f",
  git_delete = "#e85c51",
}

M.special = {
  background = "#152528",
  foreground = "#e6eaea",
  cursor = "#e6eaea",
  cursor_text = "#152528",
  selection_bg = "#293e40",
  selection_fg = "#e6eaea",
  border = "#2d4f56",
  panel = "#0f1c1e",
}

-- Semantic theme colors derived from palette
M.theme = {
  ui = {
    bg = M.palette.base00,
    bg_dim = M.palette.bg_dim or M.palette.base00,
    bg_p1 = M.palette.base01,
    bg_p2 = M.palette.base02,
    bg_m1 = M.palette.base01,
    bg_m3 = M.palette.base01,
    bg_gutter = M.palette.base00,
    bg_visual = M.palette.base02,
    bg_search = M.palette.base0A,
    fg = M.palette.base05,
    fg_dim = M.palette.base04,
    fg_reverse = M.palette.base00,
    special = M.palette.base0C,
    nontext = M.palette.base03,
    whitespace = M.palette.base02,
    float = {
      fg = M.palette.base05,
      bg = M.palette.base01,
      fg_border = M.palette.base04,
      bg_border = M.palette.base01,
    },
    pmenu = {
      fg = M.palette.base05,
      fg_sel = M.palette.base05,
      bg = M.palette.base01,
      bg_sel = M.palette.base02,
      bg_sbar = M.palette.base02,
      bg_thumb = M.palette.base03,
    },
  },
  syn = {
    comment = M.palette.syntax_comment,
    string = M.palette.syntax_string,
    number = M.palette.syntax_number,
    constant = M.palette.syntax_constant,
    identifier = M.palette.base0D,
    parameter = M.palette.syntax_parameter,
    fun = M.palette.syntax_function,
    statement = M.palette.base08,
    keyword = M.palette.syntax_keyword,
    operator = M.palette.syntax_operator,
    preproc = M.palette.syntax_preproc,
    type = M.palette.syntax_type,
    special1 = M.palette.base09,
    special2 = M.palette.base08,
    special3 = M.palette.base0C,
    punct = M.palette.base09,
    regex = M.palette.syntax_regex,
    deprecated = M.palette.base03,
  },
  diag = {
    error = M.palette.diagnostic_error,
    warning = M.palette.diagnostic_warning,
    info = M.palette.diagnostic_info,
    hint = M.palette.diagnostic_hint,
    ok = M.palette.diagnostic_ok,
  },
  vcs = {
    added = M.palette.git_add,
    changed = M.palette.git_change,
    removed = M.palette.git_delete,
  },
  diff = {
    add = "#2b4143",
    change = "#413d39",
    delete = "#543634",
    text = "#6b5448",
  },
}

return M
