-- Auto-generated palette from theme.yml
-- Theme: Unknown
-- Source: Unknown

local M = {}

M.palette = {
  -- Base16 palette
  base00 = "#242933",
  base01 = "#2E3440",
  base02 = "#3B4252",
  base03 = "#4C566A",
  base04 = "#60728A",
  base05 = "#BBC3D4",
  base06 = "#D8DEE9",
  base07 = "#E5E9F0",
  base08 = "#BF616A",
  base09 = "#D08770",
  base0A = "#EBCB8B",
  base0B = "#A3BE8C",
  base0C = "#8FBCBB",
  base0D = "#81A1C1",
  base0E = "#B48EAD",
  base0F = "#5E81AC",

  -- Extended palette
  black0 = "#191D24",
  black1 = "#1E222A",
  black2 = "#222630",
  gray0 = "#242933",
  gray1 = "#2E3440",
  gray2 = "#3B4252",
  gray3 = "#434C5E",
  gray4 = "#4C566A",
  gray5 = "#60728A",
  white0 = "#BBC3D4",
  white1 = "#D8DEE9",
  white2 = "#E5E9F0",
  white3 = "#ECEFF4",
  blue0 = "#5E81AC",
  blue1 = "#81A1C1",
  blue2 = "#88C0D0",
  red_base = "#BF616A",
  red_bright = "#C5727A",
  red_dim = "#B74E58",
  orange_base = "#D08770",
  orange_bright = "#D79784",
  orange_dim = "#CB775D",
  yellow_base = "#EBCB8B",
  yellow_bright = "#EFD49F",
  yellow_dim = "#E7C173",
  green_base = "#A3BE8C",
  green_bright = "#B1C89D",
  green_dim = "#97B67C",
  magenta_base = "#B48EAD",
  magenta_bright = "#BE9DB8",
  magenta_dim = "#A97EA1",
  cyan_base = "#8FBCBB",
  cyan_bright = "#9FC6C5",
  cyan_dim = "#80B3B2",
  syntax_comment = "#4C566A",
  syntax_string = "#A3BE8C",
  syntax_number = "#be9db8",
  syntax_constant = "#be9db8",
  syntax_variable = "#c0c8d8",
  syntax_parameter = "#c0c8d8",
  syntax_function = "#88C0D0",
  syntax_keyword = "#d08770",
  syntax_type = "#ebcb8b",
  syntax_operator = "#c0c8d8",
  syntax_punctuation = "#60728a",
  syntax_tag = "#81a1c1",
  syntax_attribute = "#ebcb8b",
  syntax_preproc = "#bf616a",
  syntax_special = "#ebcb8b",
  diagnostic_error = "#C5727A",
  diagnostic_warning = "#EBCB8B",
  diagnostic_info = "#88C0D0",
  diagnostic_hint = "#B1C89D",
  diagnostic_ok = "#A3BE8C",
  git_add = "#A3BE8C",
  git_change = "#81A1C1",
  git_delete = "#BF616A",
  git_ignored = "#4C566A",
  ui_border = "#191D24",
  ui_panel = "#191D24",
  ui_float = "#1E222A",
  ui_accent = "#88C0D0",
  ui_selection = "#3B4252",
  ui_match = "#EBCB8B",
}

M.special = {
  background = "#242933",
  foreground = "#BBC3D4",
  cursor = "#D8DEE9",
  cursor_text = "#242933",
  selection_bg = "#3B4252",
  selection_fg = "#D8DEE9",
  border = "#191D24",
  panel = "#191D24",
}

-- Semantic theme colors derived from palette
M.theme = {
  ui = {
    bg = M.palette.base00,
    bg_dim = M.palette.bg_dim or M.palette.base00,
    bg_p1 = M.palette.base01,
    bg_p2 = M.palette.base02,
    bg_m1 = M.palette.base01,
    bg_m3 = M.palette.base01,
    bg_gutter = M.palette.base00,
    bg_visual = M.palette.base02,
    bg_search = M.palette.base0A,
    fg = M.palette.base05,
    fg_dim = M.palette.base04,
    fg_reverse = M.palette.base00,
    special = M.palette.base0C,
    nontext = M.palette.base03,
    whitespace = M.palette.base02,
    float = {
      fg = M.palette.base05,
      bg = M.palette.base01,
      fg_border = M.palette.base04,
      bg_border = M.palette.base01,
    },
    pmenu = {
      fg = M.palette.base05,
      fg_sel = M.palette.base05,
      bg = M.palette.base01,
      bg_sel = M.palette.base02,
      bg_sbar = M.palette.base02,
      bg_thumb = M.palette.base03,
    },
  },
  syn = {
    comment = M.palette.syntax_comment,
    string = M.palette.syntax_string,
    number = M.palette.syntax_number,
    constant = M.palette.syntax_constant,
    identifier = M.palette.base0D,
    parameter = M.palette.syntax_parameter,
    fun = M.palette.syntax_function,
    statement = M.palette.base08,
    keyword = M.palette.syntax_keyword,
    operator = M.palette.syntax_operator,
    preproc = M.palette.syntax_preproc,
    type = M.palette.syntax_type,
    special1 = M.palette.base09,
    special2 = M.palette.base08,
    special3 = M.palette.base0C,
    punct = M.palette.base09,
    regex = M.palette.base0C,
    deprecated = M.palette.base03,
  },
  diag = {
    error = M.palette.diagnostic_error,
    warning = M.palette.diagnostic_warning,
    info = M.palette.diagnostic_info,
    hint = M.palette.diagnostic_hint,
    ok = M.palette.diagnostic_ok,
  },
  vcs = {
    added = M.palette.git_add,
    changed = M.palette.git_change,
    removed = M.palette.git_delete,
  },
  diff = {
    add = "#3b4443",
    change = "#384352",
    delete = "#563b45",
    text = "#4e5f73",
  },
}

return M
