-- Auto-generated palette from theme.yml
-- Theme: Unknown
-- Source: Unknown

local M = {}

M.palette = {
  -- Base16 palette
  base00 = "#191724",
  base01 = "#1f1d2e",
  base02 = "#26233a",
  base03 = "#6e6a86",
  base04 = "#908caa",
  base05 = "#e0def4",
  base06 = "#e0def4",
  base07 = "#524f67",
  base08 = "#eb6f92",
  base09 = "#f6c177",
  base0A = "#ebbcba",
  base0B = "#31748f",
  base0C = "#9ccfd8",
  base0D = "#c4a7e7",
  base0E = "#f6c177",
  base0F = "#524f67",

  -- Extended palette
  love = "#eb6f92",
  gold = "#f6c177",
  rose = "#ebbcba",
  pine = "#31748f",
  foam = "#9ccfd8",
  iris = "#c4a7e7",
  surface = "#1f1d2e",
  overlay = "#26233a",
  muted = "#6e6a86",
  subtle = "#908caa",
  text = "#e0def4",
  bg_dim = "#191724",
  bg0 = "#191724",
  bg1 = "#1f1d2e",
  bg2 = "#26233a",
  syntax_comment = "#6e6a86",
  syntax_string = "#31748f",
  syntax_number = "#f6c177",
  syntax_constant = "#f6c177",
  syntax_variable = "#e0def4",
  syntax_parameter = "#c4a7e7",
  syntax_function = "#c4a7e7",
  syntax_keyword = "#eb6f92",
  syntax_type = "#ebbcba",
  syntax_operator = "#908caa",
  syntax_punctuation = "#908caa",
  syntax_tag = "#eb6f92",
  syntax_attribute = "#ebbcba",
  diagnostic_error = "#eb6f92",
  diagnostic_warning = "#f6c177",
  diagnostic_info = "#9ccfd8",
  diagnostic_hint = "#c4a7e7",
  diagnostic_ok = "#31748f",
  git_add = "#31748f",
  git_change = "#f6c177",
  git_delete = "#eb6f92",
  git_ignored = "#6e6a86",
  ui_border = "#26233a",
  ui_panel = "#1f1d2e",
  ui_float = "#1f1d2e",
  ui_accent = "#c4a7e7",
  ui_selection = "#26233a",
  ui_match = "#f6c177",
}

M.special = {
  background = "#191724",
  foreground = "#e0def4",
  cursor = "#e0def4",
  cursor_text = "#191724",
  selection_bg = "#26233a",
  selection_fg = "#e0def4",
  border = "#26233a",
  panel = "#1f1d2e",
}

-- Semantic theme colors derived from palette
M.theme = {
  ui = {
    bg = M.palette.base00,
    bg_dim = M.palette.bg_dim or M.palette.base00,
    bg_p1 = M.palette.base01,
    bg_p2 = M.palette.base02,
    bg_m1 = M.palette.base01,
    bg_m3 = M.palette.base01,
    bg_gutter = M.palette.base00,
    bg_visual = M.palette.base02,
    bg_search = M.palette.base0A,
    fg = M.palette.base05,
    fg_dim = M.palette.base04,
    fg_reverse = M.palette.base00,
    special = M.palette.base0C,
    nontext = M.palette.base03,
    whitespace = M.palette.base02,
    float = {
      fg = M.palette.base05,
      bg = M.palette.base01,
      fg_border = M.palette.base04,
      bg_border = M.palette.base01,
    },
    pmenu = {
      fg = M.palette.base05,
      fg_sel = M.palette.base05,
      bg = M.palette.base01,
      bg_sel = M.palette.base02,
      bg_sbar = M.palette.base02,
      bg_thumb = M.palette.base03,
    },
  },
  syn = {
    comment = M.palette.syntax_comment,
    string = M.palette.syntax_string,
    number = M.palette.syntax_number,
    constant = M.palette.syntax_constant,
    identifier = M.palette.base0D,
    parameter = M.palette.syntax_parameter,
    fun = M.palette.syntax_function,
    statement = M.palette.base08,
    keyword = M.palette.syntax_keyword,
    operator = M.palette.syntax_operator,
    preproc = M.palette.base0C,
    type = M.palette.syntax_type,
    special1 = M.palette.base09,
    special2 = M.palette.base08,
    special3 = M.palette.base0C,
    punct = M.palette.base09,
    regex = M.palette.base0C,
    deprecated = M.palette.base03,
  },
  diag = {
    error = M.palette.diagnostic_error,
    warning = M.palette.diagnostic_warning,
    info = M.palette.diagnostic_info,
    hint = M.palette.diagnostic_hint,
    ok = M.palette.diagnostic_ok,
  },
  vcs = {
    added = M.palette.git_add,
    changed = M.palette.git_change,
    removed = M.palette.git_delete,
  },
  diff = {
    add = M.palette.base0B,
    change = M.palette.base0A,
    delete = M.palette.base08,
    text = M.palette.base0D,
  },
}

return M
