-- Auto-generated plugin highlights
local M = {}

function M.setup(colors)
  local theme = colors.theme
  return {
    -- Gitsigns
    GitSignsAdd = { fg = theme.vcs.added, bg = theme.ui.bg_gutter },
    GitSignsChange = { fg = theme.vcs.changed, bg = theme.ui.bg_gutter },
    GitSignsDelete = { fg = theme.vcs.removed, bg = theme.ui.bg_gutter },

    -- Telescope
    TelescopeBorder = { fg = theme.ui.float.fg_border, bg = theme.ui.bg },
    TelescopeTitle = { fg = theme.ui.special },
    TelescopeSelection = { link = 'CursorLine' },
    TelescopeSelectionCaret = { link = 'CursorLineNr' },
    TelescopeResultsClass = { link = 'Structure' },
    TelescopeResultsStruct = { link = 'Structure' },
    TelescopeResultsField = { link = '@variable.member' },
    TelescopeResultsMethod = { link = 'Function' },
    TelescopeResultsVariable = { link = '@variable' },
    TelescopePromptPrefix = { fg = theme.syn.fun },
    TelescopeMatching = { fg = theme.diag.warning, bold = true },

    -- blink.cmp
    BlinkCmpMenu = { link = 'Pmenu' },
    BlinkCmpMenuSelection = { link = 'PmenuSel' },
    BlinkCmpMenuBorder = { fg = theme.ui.bg_search, bg = theme.ui.pmenu.bg },
    BlinkCmpScrollBarThumb = { link = 'PmenuThumb' },
    BlinkCmpScrollBarGutter = { link = 'PmenuSbar' },
    BlinkCmpLabel = { fg = theme.ui.pmenu.fg },
    BlinkCmpLabelMatch = { fg = theme.syn.fun },
    BlinkCmpLabelDetails = { fg = theme.syn.comment },
    BlinkCmpLabelDeprecated = { fg = theme.syn.comment, strikethrough = true },
    BlinkCmpGhostText = { fg = theme.syn.comment },
    BlinkCmpDoc = { link = 'NormalFloat' },
    BlinkCmpDocBorder = { link = 'FloatBorder' },
    BlinkCmpDocCursorLine = { link = 'Visual' },
    BlinkCmpSignatureHelp = { link = 'NormalFloat' },
    BlinkCmpSignatureHelpBorder = { link = 'FloatBorder' },
    BlinkCmpSignatureHelpActiveParameter = { link = 'LspSignatureActiveParameter' },

    BlinkCmpKind = { fg = theme.ui.fg_dim },
    BlinkCmpKindText = { fg = theme.ui.fg },
    BlinkCmpKindMethod = { link = '@function.method' },
    BlinkCmpKindFunction = { link = 'Function' },
    BlinkCmpKindConstructor = { link = '@constructor' },
    BlinkCmpKindField = { link = '@variable.member' },
    BlinkCmpKindVariable = { fg = theme.ui.fg_dim },
    BlinkCmpKindClass = { link = 'Type' },
    BlinkCmpKindInterface = { link = 'Type' },
    BlinkCmpKindModule = { link = '@module' },
    BlinkCmpKindProperty = { link = '@property' },
    BlinkCmpKindUnit = { link = 'Number' },
    BlinkCmpKindValue = { link = 'String' },
    BlinkCmpKindEnum = { link = 'Type' },
    BlinkCmpKindKeyword = { link = 'Keyword' },
    BlinkCmpKindSnippet = { link = 'Special' },
    BlinkCmpKindColor = { link = 'Special' },
    BlinkCmpKindFile = { link = 'Directory' },
    BlinkCmpKindReference = { link = 'Special' },
    BlinkCmpKindFolder = { link = 'Directory' },
    BlinkCmpKindEnumMember = { link = 'Constant' },
    BlinkCmpKindConstant = { link = 'Constant' },
    BlinkCmpKindStruct = { link = 'Type' },
    BlinkCmpKindEvent = { link = 'Type' },
    BlinkCmpKindOperator = { link = 'Operator' },
    BlinkCmpKindTypeParameter = { link = 'Type' },
    BlinkCmpKindCopilot = { link = 'String' },

    -- nvim-cmp (fallback)
    CmpDocumentation = { link = 'NormalFloat' },
    CmpDocumentationBorder = { link = 'FloatBorder' },
    CmpItemAbbr = { fg = theme.ui.pmenu.fg },
    CmpItemAbbrDeprecated = { fg = theme.syn.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = theme.syn.fun },
    CmpItemAbbrMatchFuzzy = { link = 'CmpItemAbbrMatch' },
    CmpItemKindDefault = { fg = theme.ui.fg_dim },
    CmpItemMenu = { fg = theme.ui.fg_dim },
    CmpGhostText = { fg = theme.syn.comment },

    -- IndentBlankline
    IndentBlanklineChar = { fg = theme.ui.whitespace },
    IndentBlanklineSpaceChar = { fg = theme.ui.whitespace },
    IndentBlanklineSpaceCharBlankline = { fg = theme.ui.whitespace },
    IndentBlanklineContextChar = { fg = theme.ui.special },
    IndentBlanklineContextStart = { sp = theme.ui.special, underline = true },
    IblIndent = { fg = theme.ui.whitespace },
    IblWhitespace = { fg = theme.ui.whitespace },
    IblScope = { fg = theme.ui.special },

    -- Trouble
    TroubleIndent = { fg = theme.ui.whitespace },
    TroublePos = { fg = theme.ui.special },
    TroubleCount = { fg = theme.diag.warning, bold = true },
    TroubleNormal = { link = 'Normal' },
    TroubleText = { fg = theme.ui.fg },
    TroubleSource = { fg = theme.syn.comment },
    TroubleFoldIcon = { fg = theme.ui.special },
    TroubleLocation = { fg = theme.ui.nontext },

    -- Todo-comments
    TodoBgFIX = { fg = theme.ui.bg, bg = theme.diag.error, bold = true },
    TodoBgHACK = { fg = theme.ui.bg, bg = theme.diag.warning, bold = true },
    TodoBgNOTE = { fg = theme.ui.bg, bg = theme.diag.info, bold = true },
    TodoBgPERF = { fg = theme.ui.bg, bg = theme.syn.special1, bold = true },
    TodoBgTODO = { fg = theme.ui.bg, bg = theme.diag.hint, bold = true },
    TodoBgWARN = { fg = theme.ui.bg, bg = theme.diag.warning, bold = true },
    TodoFgFIX = { fg = theme.diag.error },
    TodoFgHACK = { fg = theme.diag.warning },
    TodoFgNOTE = { fg = theme.diag.info },
    TodoFgPERF = { fg = theme.syn.special1 },
    TodoFgTODO = { fg = theme.diag.hint },
    TodoFgWARN = { fg = theme.diag.warning },

    -- Which-key
    WhichKey = { fg = theme.syn.fun },
    WhichKeyGroup = { fg = theme.syn.keyword },
    WhichKeyDesc = { fg = theme.ui.fg },
    WhichKeySeperator = { fg = theme.ui.nontext },
    WhichKeySeparator = { fg = theme.ui.nontext },
    WhichKeyFloat = { bg = theme.ui.bg_m1 },
    WhichKeyBorder = { link = 'FloatBorder' },
    WhichKeyValue = { fg = theme.syn.comment },

    -- Noice
    NoiceCmdline = { fg = theme.ui.fg },
    NoiceCmdlineIcon = { fg = theme.syn.fun },
    NoiceCmdlineIconSearch = { fg = theme.diag.warning },
    NoiceCmdlinePopup = { link = 'NormalFloat' },
    NoiceCmdlinePopupBorder = { link = 'FloatBorder' },
    NoiceCmdlinePopupBorderSearch = { fg = theme.diag.warning },
    NoiceConfirm = { link = 'NormalFloat' },
    NoiceConfirmBorder = { link = 'FloatBorder' },
    NoiceFormatConfirm = { link = 'CursorLine' },
    NoiceFormatConfirmDefault = { link = 'Visual' },
    NoiceMini = { link = 'MsgArea' },
    NoicePopup = { link = 'NormalFloat' },
    NoicePopupBorder = { link = 'FloatBorder' },
    NoicePopupmenu = { link = 'Pmenu' },
    NoicePopupmenuBorder = { link = 'FloatBorder' },
    NoicePopupmenuMatch = { fg = theme.syn.fun, bold = true },
    NoicePopupmenuSelected = { link = 'PmenuSel' },
    NoiceScrollbar = { link = 'PmenuSbar' },
    NoiceScrollbarThumb = { link = 'PmenuThumb' },
    NoiceVirtualText = { fg = theme.diag.info },

    -- Oil
    OilDir = { link = 'Directory' },
    OilDirIcon = { link = 'Directory' },
    OilFile = { fg = theme.ui.fg },
    OilCreate = { fg = theme.vcs.added },
    OilDelete = { fg = theme.vcs.removed },
    OilMove = { fg = theme.vcs.changed },
    OilCopy = { fg = theme.diag.info },
    OilChange = { fg = theme.vcs.changed },
    OilRestore = { fg = theme.diag.hint },
    OilPurge = { fg = theme.diag.error },
    OilTrash = { fg = theme.diag.error },
    OilTrashSourcePath = { fg = theme.syn.comment },

    -- Bufferline
    BufferLineFill = { bg = theme.ui.bg_m3 },
    BufferLineBackground = { fg = theme.ui.nontext, bg = theme.ui.bg_m3 },
    BufferLineBuffer = { fg = theme.ui.nontext, bg = theme.ui.bg_m3 },
    BufferLineBufferSelected = { fg = theme.ui.fg, bg = theme.ui.bg, bold = true },
    BufferLineBufferVisible = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m1 },
    BufferLineCloseButton = { fg = theme.ui.nontext, bg = theme.ui.bg_m3 },
    BufferLineCloseButtonSelected = { fg = theme.diag.error, bg = theme.ui.bg },
    BufferLineCloseButtonVisible = { fg = theme.ui.nontext, bg = theme.ui.bg_m1 },
    BufferLineIndicatorSelected = { fg = theme.syn.fun, bg = theme.ui.bg },
    BufferLineModified = { fg = theme.diag.warning, bg = theme.ui.bg_m3 },
    BufferLineModifiedSelected = { fg = theme.diag.warning, bg = theme.ui.bg },
    BufferLineModifiedVisible = { fg = theme.diag.warning, bg = theme.ui.bg_m1 },
    BufferLineSeparator = { fg = theme.ui.bg_m3, bg = theme.ui.bg_m3 },
    BufferLineSeparatorSelected = { fg = theme.ui.bg_m3, bg = theme.ui.bg },
    BufferLineSeparatorVisible = { fg = theme.ui.bg_m3, bg = theme.ui.bg_m1 },
    BufferLineTab = { fg = theme.ui.nontext, bg = theme.ui.bg_m3 },
    BufferLineTabSelected = { fg = theme.ui.fg, bg = theme.ui.bg, bold = true },
    BufferLineTabClose = { fg = theme.diag.error, bg = theme.ui.bg_m3 },

    -- DAP-UI
    DapUIScope = { link = 'Special' },
    DapUIType = { link = 'Type' },
    DapUIModifiedValue = { fg = theme.syn.special1, bold = true },
    DapUIDecoration = { fg = theme.ui.float.fg_border },
    DapUIThread = { fg = theme.syn.identifier },
    DapUIStoppedThread = { fg = theme.syn.special1 },
    DapUISource = { fg = theme.syn.special2 },
    DapUILineNumber = { fg = theme.syn.special1 },
    DapUIFloatBorder = { fg = theme.ui.float.fg_border },
    DapUIWatchesEmpty = { fg = theme.diag.error },
    DapUIWatchesValue = { fg = theme.syn.identifier },
    DapUIWatchesError = { fg = theme.diag.error },
    DapUIBreakpointsPath = { link = 'Directory' },
    DapUIBreakpointsInfo = { fg = theme.diag.info },
    DapUIBreakpointsCurrentLine = { fg = theme.syn.identifier, bold = true },
    DapUIBreakpointsDisabledLine = { link = 'Comment' },
    DapUIStepOver = { fg = theme.syn.special1 },
    DapUIStepInto = { fg = theme.syn.special1 },
    DapUIStepBack = { fg = theme.syn.special1 },
    DapUIStepOut = { fg = theme.syn.special1 },
    DapUIStop = { fg = theme.diag.error },
    DapUIPlayPause = { fg = theme.syn.string },
    DapUIRestart = { fg = theme.syn.string },
    DapUIUnavailable = { fg = theme.syn.comment },

    -- Diffview
    DiffviewFilePanelTitle = { fg = theme.syn.fun, bold = true },
    DiffviewFilePanelCounter = { fg = theme.syn.constant },
    DiffviewFilePanelFileName = { fg = theme.ui.fg },
    DiffviewFilePanelPath = { fg = theme.syn.comment },
    DiffviewFilePanelInsertions = { fg = theme.vcs.added },
    DiffviewFilePanelDeletions = { fg = theme.vcs.removed },
    DiffviewStatusAdded = { fg = theme.vcs.added },
    DiffviewStatusModified = { fg = theme.vcs.changed },
    DiffviewStatusRenamed = { fg = theme.vcs.changed },
    DiffviewStatusDeleted = { fg = theme.vcs.removed },
    DiffviewStatusUntracked = { fg = theme.diag.hint },

    -- Mini
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },
    MiniIndentscopeSymbol = { fg = theme.syn.special1 },
    MiniIndentscopePrefix = { nocombine = true },
    MiniJump = { link = 'SpellRare' },
    MiniJump2dSpot = { fg = theme.syn.constant, bold = true, nocombine = true },
    MiniStatuslineDevinfo = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1 },
    MiniStatuslineFileinfo = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1 },
    MiniStatuslineFilename = { fg = theme.ui.fg_dim, bg = theme.ui.bg_dim },
    MiniStatuslineInactive = { link = 'StatusLineNC' },
    MiniStatuslineModeCommand = { fg = theme.ui.bg, bg = theme.syn.operator, bold = true },
    MiniStatuslineModeInsert = { fg = theme.ui.bg, bg = theme.diag.ok, bold = true },
    MiniStatuslineModeNormal = { fg = theme.ui.bg_m3, bg = theme.syn.fun, bold = true },
    MiniStatuslineModeOther = { fg = theme.ui.bg, bg = theme.syn.type, bold = true },
    MiniStatuslineModeReplace = { fg = theme.ui.bg, bg = theme.syn.constant, bold = true },
    MiniStatuslineModeVisual = { fg = theme.ui.bg, bg = theme.syn.keyword, bold = true },
    MiniSurround = { link = 'IncSearch' },
    MiniTrailspace = { bg = theme.vcs.removed },

    -- Lualine (via highlighting)
    LualineNormalA = { fg = theme.ui.bg, bg = theme.syn.fun, bold = true },
    LualineNormalB = { fg = theme.ui.fg, bg = theme.ui.bg_p1 },
    LualineNormalC = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m3 },
    LualineInsertA = { fg = theme.ui.bg, bg = theme.diag.ok, bold = true },
    LualineVisualA = { fg = theme.ui.bg, bg = theme.syn.keyword, bold = true },
    LualineReplaceA = { fg = theme.ui.bg, bg = theme.diag.error, bold = true },
    LualineCommandA = { fg = theme.ui.bg, bg = theme.diag.warning, bold = true },

    -- Lazy
    LazyProgressTodo = { fg = theme.ui.nontext },
    LazyProgressDone = { fg = theme.diag.ok },

    -- Notify
    NotifyBackground = { bg = theme.ui.bg },
    NotifyERRORBorder = { link = 'DiagnosticError' },
    NotifyWARNBorder = { link = 'DiagnosticWarn' },
    NotifyINFOBorder = { link = 'DiagnosticInfo' },
    NotifyHINTBorder = { link = 'DiagnosticHint' },
    NotifyDEBUGBorder = { link = 'Debug' },
    NotifyTRACEBorder = { link = 'Comment' },
    NotifyERRORIcon = { link = 'DiagnosticError' },
    NotifyWARNIcon = { link = 'DiagnosticWarn' },
    NotifyINFOIcon = { link = 'DiagnosticInfo' },
    NotifyHINTIcon = { link = 'DiagnosticHint' },
    NotifyDEBUGIcon = { link = 'Debug' },
    NotifyTRACEIcon = { link = 'Comment' },
    NotifyERRORTitle = { link = 'DiagnosticError' },
    NotifyWARNTitle = { link = 'DiagnosticWarn' },
    NotifyINFOTitle = { link = 'DiagnosticInfo' },
    NotifyHINTTitle = { link = 'DiagnosticHint' },
    NotifyDEBUGTitle = { link = 'Debug' },
    NotifyTRACETitle = { link = 'Comment' },

    -- TreesitterContext
    TreesitterContext = { link = 'Folded' },
    TreesitterContextLineNumber = { fg = theme.ui.special, bg = theme.ui.bg_gutter },

    -- Render-markdown
    RenderMarkdownH1Bg = { bg = theme.ui.bg_p1 },
    RenderMarkdownH2Bg = { bg = theme.ui.bg_p1 },
    RenderMarkdownH3Bg = { bg = theme.ui.bg_p1 },
    RenderMarkdownH4Bg = { bg = theme.ui.bg_p1 },
    RenderMarkdownH5Bg = { bg = theme.ui.bg_p1 },
    RenderMarkdownH6Bg = { bg = theme.ui.bg_p1 },
    RenderMarkdownCode = { bg = theme.ui.bg_p1 },
    RenderMarkdownCodeInline = { bg = theme.ui.bg_p1 },
    RenderMarkdownBullet = { fg = theme.syn.fun },
    RenderMarkdownQuote = { fg = theme.syn.comment, italic = true },
    RenderMarkdownDash = { fg = theme.ui.nontext },
    RenderMarkdownLink = { fg = theme.syn.special1 },
    RenderMarkdownSign = { fg = theme.ui.special },
    RenderMarkdownMath = { fg = theme.syn.constant },
    RenderMarkdownUnchecked = { fg = theme.ui.nontext },
    RenderMarkdownChecked = { fg = theme.diag.ok },
    RenderMarkdownTableHead = { fg = theme.syn.fun },
    RenderMarkdownTableRow = { fg = theme.ui.fg },
    RenderMarkdownTableFill = { link = 'Conceal' },

    -- Copilot
    CopilotSuggestion = { fg = theme.syn.comment, italic = true },
    CopilotAnnotation = { fg = theme.syn.comment, italic = true },

    -- CodeCompanion
    CodeCompanionChatHeader = { fg = theme.syn.fun, bold = true },
    CodeCompanionChatSeparator = { fg = theme.ui.nontext },
    CodeCompanionChatTokens = { fg = theme.syn.comment },
    CodeCompanionChatAgent = { fg = theme.syn.special1 },
    CodeCompanionChatTool = { fg = theme.syn.keyword },
    CodeCompanionChatVariable = { fg = theme.syn.constant },
    CodeCompanionVirtualText = { fg = theme.syn.comment, italic = true },

    -- Fidget
    FidgetTitle = { fg = theme.syn.fun },
    FidgetTask = { fg = theme.syn.comment },

    -- Health
    healthError = { fg = theme.diag.error },
    healthSuccess = { fg = theme.diag.ok },
    healthWarning = { fg = theme.diag.warning },
  }
end

return M
