-- Auto-generated palette from theme.yml
-- Theme: Unknown
-- Source: Unknown

local M = {}

M.palette = {
  -- Base16 palette
  base00 = "#171311",
  base01 = "#201b19",
  base02 = "#2a2422",
  base03 = "#73665b",
  base04 = "#a09384",
  base05 = "#e6d5c2",
  base06 = "#e6d5c2",
  base07 = "#e6d5c2",
  base08 = "#d1766e",
  base09 = "#ea9875",
  base0A = "#fcba81",
  base0B = "#99af6b",
  base0C = "#20c9cb",
  base0D = "#4e89a2",
  base0E = "#9480ba",
  base0F = "#ea9875",

  -- Extended palette
  bg_deep = "#0f0c0a",
  bg0 = "#171311",
  bg1 = "#201b19",
  bg2 = "#2a2422",
  bg3 = "#362f2c",
  bg4 = "#463e3a",
  bg5 = "#5a504c",
  fg = "#e6d5c2",
  fg_dim = "#a09384",
  comment = "#73665b",
  gutter = "#4e4641",
  brass = "#fcba81",
  ember = "#ea9875",
  sap = "#99af6b",
  cinder = "#d1766e",
  frost = "#4e89a2",
  potassium = "#9480ba",
  tint_visual = "#2f1e17",
  tint_add = "#202515",
  tint_delete = "#301d1b",
  tint_modify = "#12262e",
  syntax_comment = "#73665b",
  syntax_string = "#99af6b",
  syntax_number = "#99af6b",
  syntax_constant = "#e6d5c2",
  syntax_variable = "#e6d5c2",
  syntax_parameter = "#ea9875",
  syntax_function = "#fcba81",
  syntax_keyword = "#d1766e",
  syntax_type = "#4e89a2",
  syntax_operator = "#a09384",
  syntax_punctuation = "#a09384",
  syntax_tag = "#d1766e",
  syntax_attribute = "#ea9875",
  syntax_preproc = "#d1766e",
  syntax_special = "#ea9875",
  diagnostic_error = "#d25780",
  diagnostic_warning = "#f4a21c",
  diagnostic_info = "#58bdff",
  diagnostic_hint = "#20c9cb",
  diagnostic_ok = "#43b16a",
  git_add = "#43b16a",
  git_change = "#58bdff",
  git_delete = "#d25780",
  git_ignored = "#73665b",
  ui_border = "#362f2c",
  ui_panel = "#0f0c0a",
  ui_float = "#0f0c0a",
  ui_accent = "#ea9875",
  ui_selection = "#2f1e17",
  ui_match = "#fcba81",
}

M.special = {
  background = "#171311",
  foreground = "#e6d5c2",
  cursor = "#ea9875",
  cursor_text = "#171311",
  selection_bg = "#2f1e17",
  selection_fg = "#e6d5c2",
  border = "#362f2c",
  panel = "#0f0c0a",
}

-- Semantic theme colors derived from palette
M.theme = {
  ui = {
    bg = M.palette.base00,
    bg_dim = M.palette.bg_dim or M.palette.base00,
    bg_p1 = M.palette.base01,
    bg_p2 = M.palette.base02,
    bg_m1 = M.palette.base01,
    bg_m3 = M.palette.base01,
    bg_gutter = M.palette.base00,
    bg_visual = M.palette.base02,
    bg_search = M.palette.base0A,
    fg = M.palette.base05,
    fg_dim = M.palette.base04,
    fg_reverse = M.palette.base00,
    special = M.palette.base0C,
    nontext = M.palette.base03,
    whitespace = M.palette.base02,
    float = {
      fg = M.palette.base05,
      bg = M.palette.base01,
      fg_border = M.palette.base04,
      bg_border = M.palette.base01,
    },
    pmenu = {
      fg = M.palette.base05,
      fg_sel = M.palette.base05,
      bg = M.palette.base01,
      bg_sel = M.palette.base02,
      bg_sbar = M.palette.base02,
      bg_thumb = M.palette.base03,
    },
  },
  syn = {
    comment = M.palette.syntax_comment,
    string = M.palette.syntax_string,
    number = M.palette.syntax_number,
    constant = M.palette.syntax_constant,
    identifier = M.palette.base0D,
    parameter = M.palette.syntax_parameter,
    fun = M.palette.syntax_function,
    statement = M.palette.base08,
    keyword = M.palette.syntax_keyword,
    operator = M.palette.syntax_operator,
    preproc = M.palette.syntax_preproc,
    type = M.palette.syntax_type,
    special1 = M.palette.base09,
    special2 = M.palette.base08,
    special3 = M.palette.base0C,
    punct = M.palette.base09,
    regex = M.palette.base0C,
    deprecated = M.palette.base03,
  },
  diag = {
    error = M.palette.diagnostic_error,
    warning = M.palette.diagnostic_warning,
    info = M.palette.diagnostic_info,
    hint = M.palette.diagnostic_hint,
    ok = M.palette.diagnostic_ok,
  },
  vcs = {
    added = M.palette.git_add,
    changed = M.palette.git_change,
    removed = M.palette.git_delete,
  },
  diff = {
    add = M.palette.base0B,
    change = M.palette.base0A,
    delete = M.palette.base08,
    text = M.palette.base0D,
  },
}

return M
