-- Auto-generated palette from theme.yml
-- Theme: Unknown
-- Source: Unknown

local M = {}

M.palette = {
  -- Base16 palette
  base00 = '#1d1f21',
  base01 = '#2d2d2d',
  base02 = '#373b41',
  base03 = '#969896',
  base04 = '#969896',
  base05 = '#c5c8c6',
  base06 = '#e0e0e0',
  base07 = '#ffffff',
  base08 = '#c90d00',
  base09 = '#f79802',
  base0A = '#ffc400',
  base0B = '#60b45a',
  base0C = '#5fb3b3',
  base0D = '#4eb6fe',
  base0E = '#b294bb',
  base0F = '#c09c24',

  -- Extended palette
  dark_gray = '#1d1f21',
  medium_gray = '#2d2d2d',
  medium_light_gray = '#373b41',
  light_gray = '#969896',
  silver = '#c5c8c6',
  true_black = '#111111',
  orange = '#f79802',
  yellow = '#c09c24',
  bright_yellow = '#ffc400',
  syntax_comment = '#969896',
  syntax_string = '#60b45a',
  syntax_number = '#f79802',
  syntax_constant = '#f79802',
  syntax_variable = '#c5c8c6',
  syntax_parameter = '#b294bb',
  syntax_function = '#4eb6fe',
  syntax_keyword = '#b294bb',
  syntax_type = '#ffc400',
  syntax_operator = '#c5c8c6',
  syntax_punctuation = '#969896',
  syntax_tag = '#c90d00',
  syntax_attribute = '#ffc400',
  diagnostic_error = '#c90d00',
  diagnostic_warning = '#f79802',
  diagnostic_info = '#4eb6fe',
  diagnostic_hint = '#5fb3b3',
  diagnostic_ok = '#60b45a',
  git_add = '#60b45a',
  git_change = '#ffc400',
  git_delete = '#c90d00',
  git_ignored = '#969896',
  ui_border = '#373b41',
  ui_panel = '#2d2d2d',
  ui_float = '#1d1f21',
  ui_accent = '#4eb6fe',
  ui_selection = '#373b41',
  ui_match = '#ffc400',
}

M.special = {
  background = '#1d1f21',
  foreground = '#c5c8c6',
  cursor = '#c5c8c6',
  cursor_text = '#1d1f21',
  selection_bg = '#373b41',
  selection_fg = '#c5c8c6',
  border = '#373b41',
  panel = '#2d2d2d',
}

-- Semantic theme colors derived from palette
M.theme = {
  ui = {
    bg = M.palette.base00,
    bg_dim = M.palette.bg_dim or M.palette.base00,
    bg_p1 = M.palette.base01,
    bg_p2 = M.palette.base02,
    bg_m1 = M.palette.base01,
    bg_m3 = M.palette.base01,
    bg_gutter = M.palette.base00,
    bg_visual = M.palette.base02,
    bg_search = M.palette.base0A,
    fg = M.palette.base05,
    fg_dim = M.palette.base04,
    fg_reverse = M.palette.base00,
    special = M.palette.base0C,
    nontext = M.palette.base03,
    whitespace = M.palette.base02,
    float = {
      fg = M.palette.base05,
      bg = M.palette.base01,
      fg_border = M.palette.base04,
      bg_border = M.palette.base01,
    },
    pmenu = {
      fg = M.palette.base05,
      fg_sel = M.palette.base05,
      bg = M.palette.base01,
      bg_sel = M.palette.base02,
      bg_sbar = M.palette.base02,
      bg_thumb = M.palette.base03,
    },
  },
  syn = {
    comment = M.palette.base03,
    string = M.palette.base0B,
    number = M.palette.base0E,
    constant = M.palette.base0E,
    identifier = M.palette.base0D,
    parameter = M.palette.base0D,
    fun = M.palette.base0B,
    statement = M.palette.base08,
    keyword = M.palette.base08,
    operator = M.palette.base09,
    preproc = M.palette.base0C,
    type = M.palette.base0A,
    special1 = M.palette.base09,
    special2 = M.palette.base08,
    special3 = M.palette.base0C,
    punct = M.palette.base09,
    regex = M.palette.base0C,
    deprecated = M.palette.base03,
  },
  diag = {
    error = M.palette.base08,
    warning = M.palette.base09,
    info = M.palette.base0D,
    hint = M.palette.base0C,
    ok = M.palette.base0B,
  },
  vcs = {
    added = M.palette.base0B,
    changed = M.palette.base0A,
    removed = M.palette.base08,
  },
  diff = {
    add = M.palette.base0B,
    change = M.palette.base0A,
    delete = M.palette.base08,
    text = M.palette.base0D,
  },
}

return M
